---
default_language_version:
  node: system
  python: python3.14

repos:
  # Git Etiquette
  - repo: local
    hooks:
      - id: branch-name-check
        name: branch-name-check
        language: system
        entry: ./scripts/validate-branch-name.sh
        pass_filenames: false

  # Python linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.16.1' # keep version in sync with pyproject.toml
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: makemessages-check
        name: makemessages-check
        language: system
        entry: make makemessages-check
        pass_filenames: false
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args:
          - '--reports=n' # only display messages
          - '--output-format=colorized'
          - '--rcfile=.pylintrc'
          # add project root to sys.path to prevent django setting import errors in .github dir
          - '--init-hook=import sys; sys.path.insert(0, ".")'
          - '--django-settings-module=cms.settings.production'
          - '-j 0' # detect number of processors available to use

  - repo: https://github.com/python-poetry/poetry
    rev: '2.4.1' # keep version in sync with version installed in the Dockerfile
    hooks:
      - id: poetry-check
      - id: poetry-lock
        # Only run on changes to pyproject.toml
        files: ^pyproject.toml$

  - repo: local
    hooks:
      - id: check-poetry-version
        name: check-poetry-version
        language: system
        entry: ./scripts/check-poetry-version.sh
        pass_filenames: false
        files: ^(pyproject\.toml|poetry\.lock)$

  # Template linting
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.11
    hooks:
      - id: djhtml

  # Front-end linting
  - repo: local
    hooks:
      - id: lint:js
        name: lint:js
        language: system
        entry: npm run lint:js
        types_or: [javascript, ts]
      - id: lint:css
        name: lint:css
        language: system
        entry: npm run lint:css
        types_or: [css, scss]
      - id: lint:format
        name: lint:format
        language: system
        entry: npm run format
        types_or: [css, scss, javascript, ts, json, yaml]

  # Misc. other linters
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0 # keep version in sync with pyproject.toml
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: >
          (?x)^(
              .*/tests/.*|
              package-lock.json|
              poetry.lock|
              .*\.env.*|
              .*local\.py
          )$
